/**
 * Created by vipulkumarsharma on 25/05/16.
 */
'use strict';

    angular.module('paytmBrands',
        ['angular-carousel', 'ngTouch']
    ).config(['$compileProvider', function ($compileProvider) {
            // disable debug info
            $compileProvider.debugInfoEnabled(false);
        }]).controller('pocCtrl', function($scope) {
            //function chunk(arr, size) {
            //    var newArr = [];
            //    for (var i=0; i<arr.length; i+=size) {
            //        newArr.push(arr.slice(i, i+size));
            //    }
            //    return newArr;
            //}
            //$scope.carouselData = [
            //    {
            //        "id": 52316713,
            //        "parent_id": 52316732,
            //        "sku": "FOOADIDAS-JASO-EKAM25562080DB64EA",
            //        "priority": 1,
            //        "name": "Adidas Jaso Stripe M Slippers",
            //        "offer_price": 499,
            //        "actual_price": 1099,
            //        "tag": null,
            //        "brand": "Adidas",
            //        "vertical_id": 10,
            //        "brand_id": 1425,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOADIDAS-JASO-EKAM25562080DB64EA/1..jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "55",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/52316713",
            //        "seourl": "https://catalog.paytm.com/v1/p/adidas-jaso-stripe-m-slippers-FOOADIDAS-JASO-EKAM25562080DB64EA",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/52316713",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 44091936,
            //        "parent_id": 12268101,
            //        "sku": "HOMCROMPTON-GRESTS-662547152570D",
            //        "priority": 3,
            //        "name": "Crompton 7 Watt Led Bulbs (Pack Of 2)",
            //        "offer_price": 199,
            //        "actual_price": 750,
            //        "tag": null,
            //        "brand": "Crompton",
            //        "vertical_id": 7,
            //        "brand_id": 193706,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMCROMPTON-GRESTS-662547152570D/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "73",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/44091936",
            //        "seourl": "https://catalog.paytm.com/v1/p/crompton-greaves-7-watt-led-bulbs-pack-of-2-HOMCROMPTON-GRESTS-662547152570D",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/44091936",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49786452,
            //        "parent_id": 18079625,
            //        "sku": "STAALUMA-WALLETHEAD892259DA2351B",
            //        "priority": 4,
            //        "name": "HD Wallet Designer Card Holder - Assorted Color (Set Of 2)",
            //        "offer_price": 63,
            //        "actual_price": 299,
            //        "tag": null,
            //        "brand": "HD",
            //        "vertical_id": 37,
            //        "brand_id": 123672,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/ST/STAALUMA-WALLETHEAD892259DA2351B/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "79",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49786452",
            //        "seourl": "https://catalog.paytm.com/v1/p/aluma-wallet-designer-card-holder-black-silver-set-of-2-STAALUMA-WALLETHEAD892259DA2351B",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49786452",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 52508377,
            //        "parent_id": 52508379,
            //        "sku": "MOBBATTLANE-BL-SOFT135E6B10FEA",
            //        "priority": 5,
            //        "name": "Battlane BL-26 2600 mAh Power Bank (Assorted)",
            //        "offer_price": 107,
            //        "actual_price": 499,
            //        "tag": null,
            //        "brand": "Battlane",
            //        "vertical_id": 22,
            //        "brand_id": 462341,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/M/MO/MOBBATTLANE-BL-SOFT135E6B10FEA/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "79",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/52508377",
            //        "seourl": "https://catalog.paytm.com/v1/p/battlane-bl-26-2600-mah-power-bank-assorted-MOBBATTLANE-BL-SOFT135E6B10FEA",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/52508377",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 48269275,
            //        "parent_id": null,
            //        "sku": "KIDDEALBINDAAS-DEAL205929BC5226D",
            //        "priority": 6,
            //        "name": "DealBindaas Gun Light And Sound 1 Pc (Color May Vary)",
            //        "offer_price": 51,
            //        "actual_price": 249,
            //        "tag": null,
            //        "brand": "DealBindaas",
            //        "vertical_id": 14,
            //        "brand_id": 46977,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/K/KI/KIDDEALBINDAAS-DEAL205929BC5226D/7.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "80",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/48269275",
            //        "seourl": "https://catalog.paytm.com/v1/p/dealbindaas-gun-light-and-sound-1-pc-KIDDEALBINDAAS-DEAL205929BC5226D",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/48269275",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 18050580,
            //        "parent_id": null,
            //        "sku": "AUTVHEELOCITY-DVHEE22970D610A3C8",
            //        "priority": 7,
            //        "name": "Vheelocity Double Clamp Mobile Holder + Aux Cable + Usb Charger",
            //        "offer_price": 186,
            //        "actual_price": 599,
            //        "tag": null,
            //        "brand": "Vheelocity",
            //        "vertical_id": 43,
            //        "brand_id": 90939,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AU/AUTVHEELOCITY-DVHEE22970D610A3C8/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "69",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/18050580",
            //        "seourl": "https://catalog.paytm.com/v1/p/vheelocity-double-clamp-mobile-holder-+-aux-cable-+-usb-charger-AUTVHEELOCITY-DVHEE22970D610A3C8",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/18050580",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50693058,
            //        "parent_id": 48778586,
            //        "sku": "IND41-PCS-TOOLKSELL239462302DC94D",
            //        "priority": 8,
            //        "name": "41 PCs Toolkit Screwdriver Set",
            //        "offer_price": 199,
            //        "actual_price": 599,
            //        "tag": null,
            //        "brand": "default",
            //        "vertical_id": 58,
            //        "brand_id": 439730,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/I/IN/IND41-PCS-TOOLKSELL239462302DC94D/1.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "67",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50693058",
            //        "seourl": "https://catalog.paytm.com/v1/p/41-pcs-toolkit-screwdriver-set-IND41-PCS-TOOLKSELL239462302DC94D",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50693058",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 47747128,
            //        "parent_id": 49212630,
            //        "sku": "ACCPUMA-BROWN-LAMTS4500155445287",
            //        "priority": 9,
            //        "name": "Puma Brown Leather Wallet",
            //        "offer_price": 269,
            //        "actual_price": 1299,
            //        "tag": null,
            //        "brand": "Puma",
            //        "vertical_id": 6,
            //        "brand_id": 1447,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AC/ACCPUMA-BROWN-LAMTS4500155445287/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "79",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/47747128",
            //        "seourl": "https://catalog.paytm.com/v1/p/puma-brown-leather-wallet-ACCPUMA-BROWN-LAMTS4500155445287",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/47747128",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51441429,
            //        "parent_id": 51441433,
            //        "sku": "FOOFTR-NAVY-BLUSUNW30065F32D9B9",
            //        "priority": 10,
            //        "name": "FTR Navy Blue Sandals",
            //        "offer_price": 101,
            //        "actual_price": 499,
            //        "tag": "Save 80% on MRP",
            //        "brand": "FTR",
            //        "vertical_id": 10,
            //        "brand_id": 98859,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOFTR-NAVY-BLUSUNW30065F32D9B9/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "80",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51441429",
            //        "seourl": "https://catalog.paytm.com/v1/p/ftr-navy-blue-sandals-FOOFTR-NAVY-BLUSUNW30065F32D9B9",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51441429",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 40133179,
            //        "parent_id": null,
            //        "sku": "APPJAANVI-FASHIJAAN22447F9F08412",
            //        "priority": 11,
            //        "name": "Jaanvi Fashion Red Chiffon Saree",
            //        "offer_price": 299,
            //        "actual_price": 1200,
            //        "tag": null,
            //        "brand": "Jaanvi Fashion",
            //        "vertical_id": 2,
            //        "brand_id": 43048,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPJAANVI-FASHIJAAN22447F9F08412/1.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "75",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/40133179",
            //        "seourl": "https://catalog.paytm.com/v1/p/jaanvi-fashion-red-chiffon-saree-APPJAANVI-FASHIJAAN22447F9F08412",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/40133179",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51662664,
            //        "parent_id": null,
            //        "sku": "MOBALL-INDIA-HABIG-75157F0D45AC8",
            //        "priority": 12,
            //        "name": "All India Handicrafts Mini Selfie Stick For All Smart Phones (Assorted)",
            //        "offer_price": 66,
            //        "actual_price": 499,
            //        "tag": null,
            //        "brand": "All India Handicrafts",
            //        "vertical_id": 22,
            //        "brand_id": 461841,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/M/MO/MOBALL-INDIA-HABIG-75157F0D45AC8/1..jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "87",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51662664",
            //        "seourl": "https://catalog.paytm.com/v1/p/all-india-handicrafts-mini-selfie-stick-foe-all-s-mart-phones-assorted-MOBALL-INDIA-HABIG-75157F0D45AC8",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51662664",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 32956489,
            //        "parent_id": null,
            //        "sku": "WATLAURELS-BROWFINE206887458BFF3",
            //        "priority": 13,
            //        "name": "Laurels Brown Analog Watch",
            //        "offer_price": 98,
            //        "actual_price": 845,
            //        "tag": null,
            //        "brand": "Laurels",
            //        "vertical_id": 12,
            //        "brand_id": 18572,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/W/WA/WATLAURELS-BROWFINE206887458BFF3/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "88",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/32956489",
            //        "seourl": "https://catalog.paytm.com/v1/p/laurels-brown-analog-watch-WATLAURELS-BROWFINE206887458BFF3",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/32956489",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51340040,
            //        "parent_id": 33665820,
            //        "sku": "FOOGLOBALITE-NAGLOB222602CD8AADA2",
            //        "priority": 14,
            //        "name": "Globalite Navy And Red Casual Shoes",
            //        "offer_price": 299,
            //        "actual_price": 499,
            //        "tag": "Save 40% on MRP",
            //        "brand": "Globalite",
            //        "vertical_id": 10,
            //        "brand_id": 1846,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOGLOBALITE-NAGLOB222602CD8AADA2/2.jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "40",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51340040",
            //        "seourl": "https://catalog.paytm.com/v1/p/globalite-navy-and-red-casual-shoes-FOOGLOBALITE-NAGLOB222602CD8AADA2",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51340040",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50037510,
            //        "parent_id": 50037513,
            //        "sku": "APPZAVLIN-NAVY-ZAVL2425243CAA3802",
            //        "priority": 15,
            //        "name": "Zavlin navy cotton casual shirt",
            //        "offer_price": 299,
            //        "actual_price": 1199,
            //        "tag": null,
            //        "brand": "Zavlin",
            //        "vertical_id": 2,
            //        "brand_id": 43078,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPZAVLIN-NAVY-ZAVL2425243CAA3802/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "75",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50037510",
            //        "seourl": "https://catalog.paytm.com/v1/p/zavlin-navy-cotton-casual-shirt-APPZAVLIN-NAVY-ZAVL2425243CAA3802",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50037510",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49283288,
            //        "parent_id": null,
            //        "sku": "HOMTRIDENT-BROWSOFT111202FE4E977",
            //        "priority": 16,
            //        "name": "Trident blue And pink bath towel set of 2",
            //        "offer_price": 219,
            //        "actual_price": 900,
            //        "tag": null,
            //        "brand": "Trident",
            //        "vertical_id": 7,
            //        "brand_id": 2930,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMTRIDENT-BROWSOFT111202FE4E977/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "76",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49283288",
            //        "seourl": "https://catalog.paytm.com/v1/p/trident-brown-and-pink-bath-towel-set-of-2-HOMTRIDENT-BROWSOFT111202FE4E977",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49283288",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49119380,
            //        "parent_id": null,
            //        "sku": "MOBSELFIESEVEN-S-SA2339B39C3CD",
            //        "priority": 17,
            //        "name": "Selfieseven OTG Adaptor For All Smart Phones (Any color)",
            //        "offer_price": 58,
            //        "actual_price": 300,
            //        "tag": null,
            //        "brand": "SelfieSeven",
            //        "vertical_id": 22,
            //        "brand_id": 97958,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/M/MO/MOBSELFIESEVEN-S-SA2339B39C3CD/11.PNG",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "81",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49119380",
            //        "seourl": "https://catalog.paytm.com/v1/p/selfieseven-otg-adaptor-for-all-smart-phones-assorted-MOBSELFIESEVEN-S-SA2339B39C3CD",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49119380",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50358586,
            //        "parent_id": null,
            //        "sku": "SUNBOVC-POLARISBHAG8916362EB44ED",
            //        "priority": 18,
            //        "name": "BOVC Polarized+UV Protected Wayfarer Sunglass (Medium Size)",
            //        "offer_price": 169,
            //        "actual_price": 2490,
            //        "tag": null,
            //        "brand": "BOVC",
            //        "vertical_id": 11,
            //        "brand_id": 438369,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/SU/SUNBOVC-POLARISBHAG8916362EB44ED/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "93",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50358586",
            //        "seourl": "https://catalog.paytm.com/v1/p/bovc-polarised-uv-protection-sunglasses-SUNBOVC-POLARISBHAG8916362EB44ED",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50358586",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50229496,
            //        "parent_id": 22541591,
            //        "sku": "FOOLOTTO-ORANGEGLOB2226025FD541F4",
            //        "priority": 19,
            //        "name": "Lotto Orange Slippers",
            //        "offer_price": 161,
            //        "actual_price": 449,
            //        "tag": "Save 67% on MRP",
            //        "brand": "Lotto",
            //        "vertical_id": 10,
            //        "brand_id": 1847,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOLOTTO-ORANGEGLOB2226025FD541F4/2.jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "64",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50229496",
            //        "seourl": "https://catalog.paytm.com/v1/p/lotto-orange-slippers-FOOLOTTO-ORANGEGLOB2226025FD541F4",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50229496",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 11383490,
            //        "parent_id": null,
            //        "sku": "HOMWALLTOLA-HEAWALL58330D6E21575",
            //        "priority": 20,
            //        "name": "WallTola Heart Leaves Branch Wall Sticker",
            //        "offer_price": 55,
            //        "actual_price": 449,
            //        "tag": null,
            //        "brand": "WallTola",
            //        "vertical_id": 7,
            //        "brand_id": 175422,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMWALLTOLA-HEAWALL58330D6E21575/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "88",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/11383490",
            //        "seourl": "https://catalog.paytm.com/v1/p/walltola-heart-leaves-branch-wall-sticker-HOMWALLTOLA-HEAWALL58330D6E21575",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/11383490",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 22133976,
            //        "parent_id": null,
            //        "sku": "APPVAAMSI-CREAMVAAM2105937394849",
            //        "priority": 21,
            //        "name": "Vaamsi Cream Unstitched Dress Material",
            //        "offer_price": 189,
            //        "actual_price": 1500,
            //        "tag": null,
            //        "brand": "Vaamsi",
            //        "vertical_id": 2,
            //        "brand_id": 47047,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPVAAMSI-CREAMVAAM2105937394849/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "87",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/22133976",
            //        "seourl": "https://catalog.paytm.com/v1/p/vaamsi-cream-cotton-dress-material-APPVAAMSI-CREAMVAAM2105937394849",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/22133976",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 34250911,
            //        "parent_id": null,
            //        "sku": "ACCELLIGATOR-BLAGAR150476AEA33",
            //        "priority": 22,
            //        "name": "Elligator Black And Brown Combo Of 2 Belts",
            //        "offer_price": 109,
            //        "actual_price": 998,
            //        "tag": null,
            //        "brand": "Elligator",
            //        "vertical_id": 6,
            //        "brand_id": 18355,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AC/ACCELLIGATOR-BLAGAR150476AEA33/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "89",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/34250911",
            //        "seourl": "https://catalog.paytm.com/v1/p/elligator-black-and-brown-combo-of-2-belts-ACCELLIGATOR-BLAGAR150476AEA33",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/34250911",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51747085,
            //        "parent_id": 16351470,
            //        "sku": "HOMSNAPSHOPEE-2VAIB241309BB520397",
            //        "priority": 23,
            //        "name": "Snapshopee 200 Ml Stainless Steel Mug (Set Of 1)",
            //        "offer_price": 79,
            //        "actual_price": 1999,
            //        "tag": null,
            //        "brand": "Snapshopee",
            //        "vertical_id": 7,
            //        "brand_id": 164743,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMSNAPSHOPEE-2VAIB241309BB520397/2.jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "96",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51747085",
            //        "seourl": "https://catalog.paytm.com/v1/p/snapshopee-200-ml-stainless-steel-mug-set-of-1-HOMSNAPSHOPEE-2VAIB241309BB520397",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51747085",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 52129087,
            //        "parent_id": null,
            //        "sku": "APPINDIAN-BEAUTSHRI512917A257DDA",
            //        "priority": 24,
            //        "name": "Indian Beauty Designer Miss India Black Dress",
            //        "offer_price": 279,
            //        "actual_price": 999,
            //        "tag": null,
            //        "brand": "Indian Beauty",
            //        "vertical_id": 2,
            //        "brand_id": 144380,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPINDIAN-BEAUTSHRI512917A257DDA/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "72",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/52129087",
            //        "seourl": "https://catalog.paytm.com/v1/p/indian-beauty-designer-miss-india-black-dress-APPINDIAN-BEAUTSHRI512917A257DDA",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/52129087",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 20344494,
            //        "parent_id": 20345491,
            //        "sku": "BAGBUTTERFLIES-BUTT85276580E1CA8",
            //        "priority": 25,
            //        "name": "Butterflies Maroon Wallet",
            //        "offer_price": 199,
            //        "actual_price": 1099,
            //        "tag": "30% Extra",
            //        "brand": "Butterflies",
            //        "vertical_id": 9,
            //        "brand_id": 17865,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/B/BA/BAGBUTTERFLIES-BUTT85276580E1CA8/17.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "82",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/20344494",
            //        "seourl": "https://catalog.paytm.com/v1/p/butterflies-maroon-wallet-BAGBUTTERFLIES-BUTT85276580E1CA8",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/20344494",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 44188493,
            //        "parent_id": null,
            //        "sku": "HOMELPH-DISPOSAESS_24216FED4BDF7",
            //        "priority": 26,
            //        "name": "ELPH Disposable Garbage Bags Set of 40",
            //        "offer_price": 79,
            //        "actual_price": 299,
            //        "tag": null,
            //        "brand": "ELPH",
            //        "vertical_id": 7,
            //        "brand_id": 454453,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMELPH-DISPOSAESS_24216FED4BDF7/2..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "74",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/44188493",
            //        "seourl": "https://catalog.paytm.com/v1/p/elph-disposable-garbage-bags-set-of-40-HOMELPH-DISPOSAESS_24216FED4BDF7",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/44188493",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50944862,
            //        "parent_id": null,
            //        "sku": "APPINDIAN-BEAUTSHRI51291B489774C",
            //        "priority": 27,
            //        "name": "Indian Beauty Yellow Georgette Sari",
            //        "offer_price": 299,
            //        "actual_price": 1157,
            //        "tag": null,
            //        "brand": "default",
            //        "vertical_id": 2,
            //        "brand_id": 439730,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPINDIAN-BEAUTSHRI51291B489774C/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "74",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50944862",
            //        "seourl": "https://catalog.paytm.com/v1/p/indian-beauty-yellow-georgette-sari-APPINDIAN-BEAUTSHRI51291B489774C",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50944862",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51793843,
            //        "parent_id": null,
            //        "sku": "ACCELLIGATOR-COAGAR150E15D3E56",
            //        "priority": 28,
            //        "name": "Elligator Combo of Gym bag  Belt  Wallet And Aviator",
            //        "offer_price": 299,
            //        "actual_price": 1999,
            //        "tag": null,
            //        "brand": "Elligator",
            //        "vertical_id": 6,
            //        "brand_id": 18355,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AC/ACCELLIGATOR-COAGAR150E15D3E56/15.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "85",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51793843",
            //        "seourl": "https://catalog.paytm.com/v1/p/elligator-combo-of-gym-bag-belt-wallet-and-aviator-ACCELLIGATOR-COAGAR150E15D3E56",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51793843",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 289601,
            //        "parent_id": null,
            //        "sku": "HKTOOL0000AI_114ABNAFR",
            //        "priority": 29,
            //        "name": "Amiraj Nut Cutter",
            //        "offer_price": 79,
            //        "actual_price": 350,
            //        "tag": null,
            //        "brand": "Amiraj",
            //        "vertical_id": 7,
            //        "brand_id": 2774,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HK/HKTOOL0000AI_114ABNAFR/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "77",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/289601",
            //        "seourl": "https://catalog.paytm.com/v1/p/amiraj-nut-cutter-hktool0000ai_114abnafr",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/289601",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 47574329,
            //        "parent_id": 47574335,
            //        "sku": "FOOACTION-SHOESMICR55641F6639598",
            //        "priority": 30,
            //        "name": "Action Shoes Dotcom Men Casual Shoes A-352-Olive",
            //        "offer_price": 999,
            //        "actual_price": 999,
            //        "tag": "Save 40% on MRP",
            //        "brand": "Action",
            //        "vertical_id": 10,
            //        "brand_id": 20724,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOACTION-SHOESMICR55641F6639598/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "0",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/47574329",
            //        "seourl": "https://catalog.paytm.com/v1/p/action-shoes-dotcom-men-casual-shoes-a-352-olive-FOOACTION-SHOESMICR55641F6639598",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/47574329",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 34031542,
            //        "parent_id": 19487238,
            //        "sku": "STOSANDISK-ULTRVAIS1444041C610E04",
            //        "priority": 31,
            //        "name": "SanDisk Ultra Dual USB 3.0 16 GB USB OTG Pen Drive (Black)",
            //        "offer_price": 412,
            //        "actual_price": 1099,
            //        "tag": "+12% CB",
            //        "brand": "SanDisk",
            //        "vertical_id": 19,
            //        "brand_id": 2652,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/ST/STOSANDISK-ULTRVAIS1444041C610E04/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "63",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/34031542",
            //        "seourl": "https://catalog.paytm.com/v1/p/sandisk-ultra-dual-usb-3-0-16-gb-otg-flash-drive-black-STOSANDISK-ULTRVAIS1444041C610E04",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/34031542",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 7472823,
            //        "parent_id": 11103741,
            //        "sku": "HOMEVEREADY-12-OVER134DF482F93",
            //        "priority": 32,
            //        "name": "Eveready 12 Watt Cool Day Light LED Bulb - Pack Of 2",
            //        "offer_price": 499,
            //        "actual_price": 699,
            //        "tag": null,
            //        "brand": "Eveready",
            //        "vertical_id": 7,
            //        "brand_id": 2790,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMEVEREADY-12-OVER134DF482F93/3.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "29",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/7472823",
            //        "seourl": "https://catalog.paytm.com/v1/p/eveready-12-watt-cool-day-light-led-bulb-pack-of-2-HOMEVEREADY-12-OVER134DF482F93",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/7472823",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 3115592,
            //        "parent_id": 3115597,
            //        "sku": "SIGNORACARE_SCEP-2911_500W_NULL_21273",
            //        "priority": 33,
            //        "name": "SignoraCare Eco Plus 500 W Mixer Grinder (White & Blue/2 Jar)",
            //        "offer_price": 1219,
            //        "actual_price": 1790,
            //        "tag": "+25% CB",
            //        "brand": "SignoraCare",
            //        "vertical_id": 30,
            //        "brand_id": 33123,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/SI/SIGNORACARE_SCEP-2911_500W_NULL_21273/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "32",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/3115592",
            //        "seourl": "https://catalog.paytm.com/v1/p/signoracare-eco-plus-500-watts-SIGNORACARE_SCEP-2911_500W_NULL_21273",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/3115592",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49505051,
            //        "parent_id": 4905230,
            //        "sku": "PERBLM-BEATY-CRKRIS2727578AB0BFF",
            //        "priority": 34,
            //        "name": "BLM Beaty Crown Hair Dryer For Women (Pink)",
            //        "offer_price": 549,
            //        "actual_price": 1000,
            //        "tag": "+75% CB",
            //        "brand": "BLM",
            //        "vertical_id": 24,
            //        "brand_id": 51757,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/P/PE/PERBLM-BEATY-CRKRIS2727578AB0BFF/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "45",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49505051",
            //        "seourl": "https://catalog.paytm.com/v1/p/blm-beaty-crown-hair-dryer-for-women-pink-PERBLM-BEATY-CRKRIS2727578AB0BFF",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49505051",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 42678699,
            //        "parent_id": 42678701,
            //        "sku": "WATMAXIMA-BLACKAMAI6713636C92C7E",
            //        "priority": 35,
            //        "name": "Maxima Black Analog Watch",
            //        "offer_price": 159,
            //        "actual_price": 2499,
            //        "tag": null,
            //        "brand": "Maxima",
            //        "vertical_id": 12,
            //        "brand_id": 1532,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/W/WA/WATMAXIMA-BLACKAMAI6713636C92C7E/5.JPG",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "94",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/42678699",
            //        "seourl": "https://catalog.paytm.com/v1/p/maxima-black-analog-watch-WATMAXIMA-BLACKAMAI6713636C92C7E",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/42678699",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49891406,
            //        "parent_id": null,
            //        "sku": "APPVAAMSI-SALWAVAAM21059A17226B9",
            //        "priority": 36,
            //        "name": "Vaamsi Salwar Suits Dress Material",
            //        "offer_price": 189,
            //        "actual_price": 999,
            //        "tag": null,
            //        "brand": "Vaamsi",
            //        "vertical_id": 2,
            //        "brand_id": 47047,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPVAAMSI-SALWAVAAM21059A17226B9/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "81",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49891406",
            //        "seourl": "https://catalog.paytm.com/v1/p/vaamsi-salwar-suits-dress-material-APPVAAMSI-SALWAVAAM21059A17226B9",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49891406",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 45340277,
            //        "parent_id": 24866880,
            //        "sku": "PERBLUE-ME-BMNHKRIS27275FC4F85BB",
            //        "priority": 37,
            //        "name": "Blue Me BMNHC3915 Trimmer For Men (White )",
            //        "offer_price": 625,
            //        "actual_price": 1200,
            //        "tag": "+75% CB",
            //        "brand": "Blue Me",
            //        "vertical_id": 24,
            //        "brand_id": 299534,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/P/PE/PERBLUE-ME-BMNHKRIS27275FC4F85BB/2.jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "48",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/45340277",
            //        "seourl": "https://catalog.paytm.com/v1/p/blue-me-bmnhc3915-trimmer-for-men-white-PERBLUE-ME-BMNHKRIS27275FC4F85BB",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/45340277",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 52714532,
            //        "parent_id": null,
            //        "sku": "KIDHIMALAYA-BABMOKS31619A1F3513D",
            //        "priority": 38,
            //        "name": "Himalaya Baby Gift BOX 2SP",
            //        "offer_price": 89,
            //        "actual_price": 150,
            //        "tag": null,
            //        "brand": "Himalaya",
            //        "vertical_id": 14,
            //        "brand_id": 34605,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/K/KI/KIDHIMALAYA-BABMOKS31619A1F3513D/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "41",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/52714532",
            //        "seourl": "https://catalog.paytm.com/v1/p/himalaya-baby-gift-box-2sp-KIDHIMALAYA-BABMOKS31619A1F3513D",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/52714532",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 48230284,
            //        "parent_id": null,
            //        "sku": "COMSUNDAY-BAZARTECH202718250764E",
            //        "priority": 39,
            //        "name": "Philips SHE1405BK Wired In Ear Headset (Black)",
            //        "offer_price": 238,
            //        "actual_price": 349,
            //        "tag": null,
            //        "brand": "Philips",
            //        "vertical_id": 23,
            //        "brand_id": 2573,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/C/CO/COMSUNDAY-BAZARTECH202718250764E/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "32",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/48230284",
            //        "seourl": "https://catalog.paytm.com/v1/p/sunday-bazar-34-COMSUNDAY-BAZARTECH202718250764E",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/48230284",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 2324366,
            //        "parent_id": null,
            //        "sku": "WBAGSS0000000G29KCBGFR",
            //        "priority": 40,
            //        "name": "Borse Beige Sling Bag",
            //        "offer_price": 295,
            //        "actual_price": 1669,
            //        "tag": null,
            //        "brand": "Borse",
            //        "vertical_id": 9,
            //        "brand_id": 18325,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/W/WB/WBAGSS0000000G29KCBGFR/2.JPG",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "82",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/2324366",
            //        "seourl": "https://catalog.paytm.com/v1/p/borse-beige-sling-with-polyester-strap-WBAGSS0000000G29KCBGFR",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/2324366",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 20474784,
            //        "parent_id": 20475137,
            //        "sku": "APPAVE-MULTI-COA-V-36411C32B6CF8",
            //        "priority": 41,
            //        "name": "Ave Multi Color Cotton Pack Of 2 T-Shirt",
            //        "offer_price": 249,
            //        "actual_price": 888,
            //        "tag": null,
            //        "brand": "Ave",
            //        "vertical_id": 2,
            //        "brand_id": 85302,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPAVE-MULTI-COA-V-36411C32B6CF8/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "72",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/20474784",
            //        "seourl": "https://catalog.paytm.com/v1/p/ave-multi-color-cotton-pack-of-2-t-shirt-size-m-APPAVE-MULTI-COA-V-36411C32B6CF8",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/20474784",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49111336,
            //        "parent_id": 44989225,
            //        "sku": "SPOYUIME-THREE-PICK21852471DFB3F7",
            //        "priority": 42,
            //        "name": "Yuime Three Travelling Treasures Kit Neck Cushion Pillow With Two Ear Buds And Eye Mask",
            //        "offer_price": 110,
            //        "actual_price": 699,
            //        "tag": null,
            //        "brand": "Yuime",
            //        "vertical_id": 15,
            //        "brand_id": 442439,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/SP/SPOYUIME-THREE-PICK21852471DFB3F7/1.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "84",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49111336",
            //        "seourl": "https://catalog.paytm.com/v1/p/yuime-three-travelling-treasures-kit-neck-cushion-pillow-with-two-ear-buds-and-eye-mask-SPOYUIME-THREE-PICK21852471DFB3F7",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49111336",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 13484070,
            //        "parent_id": 13484341,
            //        "sku": "FOOWOODLAND-BLAAERO21259BA8B8377",
            //        "priority": 43,
            //        "name": "Woodland Black Nubuk Casual Shoes",
            //        "offer_price": 3895,
            //        "actual_price": 3895,
            //        "tag": "30% Cash Back",
            //        "brand": "Woodland",
            //        "vertical_id": 10,
            //        "brand_id": 1817,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOOWOODLAND-BLAAERO21259BA8B8377/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "0",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/13484070",
            //        "seourl": "https://catalog.paytm.com/v1/p/woodland-black-nubuk-casual-shoes-size-39-FOOWOODLAND-BLAAERO21259BA8B8377",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/13484070",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 20366993,
            //        "parent_id": 6894653,
            //        "sku": "STOSAMSUNG-MICRJIPL2932441E5288",
            //        "priority": 44,
            //        "name": "Samsung Evo MicroSDHC 16 GB Class 10 Memory Card",
            //        "offer_price": 322,
            //        "actual_price": 599,
            //        "tag": "+12% CB",
            //        "brand": "Samsung",
            //        "vertical_id": 19,
            //        "brand_id": 2578,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/ST/STOSAMSUNG-MICRJIPL2932441E5288/2.jpeg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "46",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/20366993",
            //        "seourl": "https://catalog.paytm.com/v1/p/samsung-microsdhc-16-gb-class-10-evo-UNDEFINEDSTOSAMSUNG-MICRJIPL2932441E5288",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/20366993",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 50860422,
            //        "parent_id": null,
            //        "sku": "KIDDEALBINDAAS-DEAL205921618D751",
            //        "priority": 45,
            //        "name": "DealBindaas Remote Car Sonic Control (Color May Vary)",
            //        "offer_price": 99,
            //        "actual_price": 249,
            //        "tag": null,
            //        "brand": "DealBindaas",
            //        "vertical_id": 14,
            //        "brand_id": 46977,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/K/KI/KIDDEALBINDAAS-DEAL205921618D751/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "60",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/50860422",
            //        "seourl": "https://catalog.paytm.com/v1/p/dealbindaas-remote-car-sonic-control-KIDDEALBINDAAS-DEAL205921618D751",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/50860422",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 47975108,
            //        "parent_id": null,
            //        "sku": "SPOBODY-MAXX-LEKUKU218101B8236F6",
            //        "priority": 46,
            //        "name": "Body Maxx Leather Multipurpose Gym Gloves With Padded Palm Support & Net Upside",
            //        "offer_price": 65,
            //        "actual_price": 300,
            //        "tag": null,
            //        "brand": "KKD",
            //        "vertical_id": 15,
            //        "brand_id": 33645,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/SP/SPOBODY-MAXX-LEKUKU218101B8236F6/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "78",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/47975108",
            //        "seourl": "https://catalog.paytm.com/v1/p/body-maxx-leather-multipurpose-gym-gloves-with-padded-palm-support-net-upside-SPOBODY-MAXX-LEKUKU218101B8236F6",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/47975108",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 11383327,
            //        "parent_id": null,
            //        "sku": "HOMWALLTOLA-BABWALL5833059F82F58",
            //        "priority": 47,
            //        "name": "WallTola Baby Cartoon Animal Kingdom Kids Room Wall Sticker",
            //        "offer_price": 55,
            //        "actual_price": 650,
            //        "tag": null,
            //        "brand": "WallTola",
            //        "vertical_id": 7,
            //        "brand_id": 175422,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMWALLTOLA-BABWALL5833059F82F58/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "92",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/11383327",
            //        "seourl": "https://catalog.paytm.com/v1/p/walltola-baby-cartoon-animal-kingdom-kids-room-wall-sticker-HOMWALLTOLA-BABWALL5833059F82F58",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/11383327",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51310610,
            //        "parent_id": 51310633,
            //        "sku": "FOORED-TAPE-MENRED-2509794C49D22E",
            //        "priority": 48,
            //        "name": "Red Tape Men BLACK Leather Formals",
            //        "offer_price": 1977,
            //        "actual_price": 3295,
            //        "tag": "+25% CB",
            //        "brand": "Red Tape",
            //        "vertical_id": 10,
            //        "brand_id": 1451,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/F/FO/FOORED-TAPE-MENRED-2509794C49D22E/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "40",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51310610",
            //        "seourl": "https://catalog.paytm.com/v1/p/red-tape-men-black-leather-formals-FOORED-TAPE-MENRED-2509794C49D22E",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51310610",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 40761307,
            //        "parent_id": 26213374,
            //        "sku": "COMJBL-PULSE-2-GLOB20346413294DB3",
            //        "priority": 49,
            //        "name": "JBL Pulse 2 Bluetooth Speaker (Black)",
            //        "offer_price": 11599,
            //        "actual_price": 17990,
            //        "tag": "+10% CB",
            //        "brand": "JBL",
            //        "vertical_id": 23,
            //        "brand_id": 2906,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/C/CO/COMJBL-PULSE-2-GLOB20346413294DB3/2.png",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "36",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/40761307",
            //        "seourl": "https://catalog.paytm.com/v1/p/jbl-pulse-2-bluetooth-speaker-black-COMJBL-PULSE-2-GLOB20346413294DB3",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/40761307",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49943242,
            //        "parent_id": 49943246,
            //        "sku": "APPWAJBEE-MEN-SS-A-23919B82DD356",
            //        "priority": 50,
            //        "name": "Wajbee Men's 100% Cotton Casual Shirt",
            //        "offer_price": 399,
            //        "actual_price": 1740,
            //        "tag": null,
            //        "brand": "Wajbee",
            //        "vertical_id": 2,
            //        "brand_id": 140201,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPWAJBEE-MEN-SS-A-23919B82DD356/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "77",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49943242",
            //        "seourl": "https://catalog.paytm.com/v1/p/wajbee-men-s-100-cotton-casual-shirt-APPWAJBEE-MEN-SS-A-23919B82DD356",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49943242",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49494892,
            //        "parent_id": 3129592,
            //        "sku": "PERPHILIPS-BT32SHAU119678699738E7",
            //        "priority": 51,
            //        "name": "Philips BT3200/15 Corded Trimmer For Men (Black)",
            //        "offer_price": 940,
            //        "actual_price": 1095,
            //        "tag": null,
            //        "brand": "Philips",
            //        "vertical_id": 24,
            //        "brand_id": 2573,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/P/PE/PERPHILIPS-BT32SHAU119678699738E7/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "14",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49494892",
            //        "seourl": "https://catalog.paytm.com/v1/p/philips-bt3200-15-corded-trimmer-for-men-black-PERPHILIPS-BT32SHAU119678699738E7",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49494892",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 21100697,
            //        "parent_id": 22444416,
            //        "sku": "BAGAMERICAN-TOUVIRA203381B128ADF",
            //        "priority": 52,
            //        "name": "American Tourister Yellow Polyester    (Non-laptop Backpack)",
            //        "offer_price": 1150,
            //        "actual_price": 1150,
            //        "tag": "Extra Cashback",
            //        "brand": "American Tourister",
            //        "vertical_id": 9,
            //        "brand_id": 1632,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/B/BA/BAGAMERICAN-TOUVIRA203381B128ADF/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "0",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/21100697",
            //        "seourl": "https://catalog.paytm.com/v1/p/american-tourister-yellow-polyester-backpack-BAGAMERICAN-TOUVIRA203381B128ADF",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/21100697",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49322535,
            //        "parent_id": 45854140,
            //        "sku": "HOMSRK-INTERNATSHOP225845171DB7",
            //        "priority": 53,
            //        "name": "Shopper52 Toothpaste Dispenser",
            //        "offer_price": 139,
            //        "actual_price": 799,
            //        "tag": null,
            //        "brand": "Shopper52",
            //        "vertical_id": 7,
            //        "brand_id": 46555,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/H/HO/HOMSRK-INTERNATSHOP225845171DB7/1.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "83",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49322535",
            //        "seourl": "https://catalog.paytm.com/v1/p/srk-internationals-toothpaste-dispenser-HOMSRK-INTERNATSHOP225845171DB7",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49322535",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 48348615,
            //        "parent_id": 51189999,
            //        "sku": "BEAVINAYAKA-EYEVINA39590E0AB4ED3",
            //        "priority": 54,
            //        "name": "Vinayaka Eye Cool Mask",
            //        "offer_price": 69,
            //        "actual_price": 325,
            //        "tag": null,
            //        "brand": "Vinayaka",
            //        "vertical_id": 31,
            //        "brand_id": 302874,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/B/BE/BEAVINAYAKA-EYEVINA39590E0AB4ED3/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "79",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/48348615",
            //        "seourl": "https://catalog.paytm.com/v1/p/vinayaka-eye-cool-mask-BEAVINAYAKA-EYEVINA39590E0AB4ED3",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/48348615",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49984305,
            //        "parent_id": null,
            //        "sku": "KIDSTOL-N-GIRLSCOMM31390C267C6B2",
            //        "priority": 55,
            //        "name": "Stol'n Girls Tweety (Licensed) Cateye Sunglasses - White&Pink",
            //        "offer_price": 99,
            //        "actual_price": 395,
            //        "tag": null,
            //        "brand": "Stol'n",
            //        "vertical_id": 14,
            //        "brand_id": 92745,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/K/KI/KIDSTOL-N-GIRLSCOMM31390C267C6B2/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "75",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49984305",
            //        "seourl": "https://catalog.paytm.com/v1/p/stol-n-girls-tweety-cateye-sunglasses-white-pink-KIDSTOL-N-GIRLSCOMM31390C267C6B2",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49984305",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 22962648,
            //        "parent_id": 9281696,
            //        "sku": "SPOANTI-SKID-YOGPA-83546A37761FD",
            //        "priority": 56,
            //        "name": "Anti Skid Yoga Mat 4MM Thick Washable Fitness Exercise Imported Non-Slip",
            //        "offer_price": 199,
            //        "actual_price": 599,
            //        "tag": null,
            //        "brand": "Yoga",
            //        "vertical_id": 15,
            //        "brand_id": 131878,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/S/SP/SPOANTI-SKID-YOGPA-83546A37761FD/3.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "67",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/22962648",
            //        "seourl": "https://catalog.paytm.com/v1/p/anti-skid-yoga-mat-4mm-thick-washable-fitness-exercise-imported-non-slip-surface-4mm-thickness-makes-yoga-exercise-feels-good-reshamcreation214-SPOANTI-SKID-YOGPA-83546A37761FD",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/22962648",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49091340,
            //        "parent_id": null,
            //        "sku": "APPSTYLE-AMAZE-STYL360581EF02FE",
            //        "priority": 57,
            //        "name": "Style Amaze Presents Pink Designer Salwar Suit",
            //        "offer_price": 349,
            //        "actual_price": 2279,
            //        "tag": null,
            //        "brand": "STYLE AMAZE",
            //        "vertical_id": 2,
            //        "brand_id": 122604,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AP/APPSTYLE-AMAZE-STYL360581EF02FE/3.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "85",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49091340",
            //        "seourl": "https://catalog.paytm.com/v1/p/style-amaze-presents-pink-designer-salwar-suit-APPSTYLE-AMAZE-STYL360581EF02FE",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49091340",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 34195737,
            //        "parent_id": null,
            //        "sku": "KIDORANGE-AND-BLUXU6524037E7B058",
            //        "priority": 58,
            //        "name": "Kids Orange And Black Plastic Round Digital Watch",
            //        "offer_price": 84,
            //        "actual_price": 249,
            //        "tag": null,
            //        "brand": "default",
            //        "vertical_id": 14,
            //        "brand_id": 439730,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/K/KI/KIDORANGE-AND-BLUXU6524037E7B058/2.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "66",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/34195737",
            //        "seourl": "https://catalog.paytm.com/v1/p/orange-and-black-plastic-round-digital-watch-KIDORANGE-AND-BLUXU6524037E7B058",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/34195737",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 49925744,
            //        "parent_id": 49925745,
            //        "sku": "COMQUANTUM-HS65S-SA2333795A218",
            //        "priority": 59,
            //        "name": "PMG Mobile portable mini speaker ( any color )",
            //        "offer_price": 156,
            //        "actual_price": 399,
            //        "tag": null,
            //        "brand": "PMG",
            //        "vertical_id": 23,
            //        "brand_id": 461041,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/C/CO/COMQUANTUM-HS65S-SA2333795A218/13.jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "61",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/49925744",
            //        "seourl": "https://catalog.paytm.com/v1/p/quantum-hs656-assorted-COMQUANTUM-HS65S-SA2333795A218",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/49925744",
            //        "view_item_id": 46739
            //    },
            //    {
            //        "id": 51244926,
            //        "parent_id": null,
            //        "sku": "ACCSKYWAYS-BELTSKYW2042573B0C78F",
            //        "priority": 60,
            //        "name": "Skyways Belts combo-set of 2",
            //        "offer_price": 99,
            //        "actual_price": 600,
            //        "tag": null,
            //        "brand": "SkyWays",
            //        "vertical_id": 6,
            //        "brand_id": 18121,
            //        "image_url": "https://assetscdn.paytm.com/images/catalog/product/A/AC/ACCSKYWAYS-BELTSKYW2042573B0C78F/1..jpg",
            //        "stock": true,
            //        "img_width": 400,
            //        "img_height": 400,
            //        "discount": "84",
            //        "url_type": "product",
            //        "url": "https://catalog.paytm.com/v1/mobile/product/51244926",
            //        "seourl": "https://catalog.paytm.com/v1/p/skyways-belts-combo-set-of-2-ACCSKYWAYS-BELTSKYW2042573B0C78F",
            //        "delete_url": "https://catalogadmin.paytm.com/v1/admin/storefront//group//product/51244926",
            //        "view_item_id": 46739
            //    }
            //];
            //$scope.chunkedCarouselData = chunk($scope.carouselData, 4);
            //$scope.brandStoreId = Math.floor(Math.random()*90000) + 10000;

            $scope.saveWidgetData = function() {
                var formData = {
                    widgetName: $scope.widgetName,
                    isActive : $scope.isActive,
                    widgetJs : $scope.widgetJs,
                    widgetCss: $scope.widgetCss,
                    widgetTemplate: $scope.widgetTemplate
                };
                console.log(formData);
                localStorage.directiveData = JSON.stringify(formData);
                console.log(localStorage.directiveData);
            };
        })/*.directive('paytmBrandsCarousel', function() {
            return {
                restrict: 'E',
                scope: {
                    carouselItems: '=items'
                },
                link : function(scope, attrs, elem) {
                    scope.testSharingFunction = function() {
                        console.log('is shared');
                    }
                  console.log(scope.carouselItems);
                },
                templateUrl: 'directivesHtml/carousel.html'
            }
        });*/
